# -*- coding: utf-8 -*-
"""KeaBuilder_scriptcode.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dL9tQMCYnY2XmeqFy_wVtaQ-H449y-RB
"""

import numpy as np

# 1. CORE SIMILARITY LOGIC
def get_cosine_similarity(v1, v2):
    """Calculates how similar two inputs are (1.0 is identical)."""
    return np.dot(v1, v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))

# 2. SYSTEM DATA (3-5 Sample Inputs as Vectors)
# Representing potential KeaBuilder lead categories
knowledge_base = {
    "Technical_Support": [0.9, 0.1, 0.1],
    "Sales_Inquiry": [0.1, 0.8, 0.2],
    "Partnership_Lead": [0.1, 0.2, 0.9],
    "Billing_Question": [0.7, 0.1, 0.7]
}

# 3. MATCHING ENGINE
def find_top_match(user_query_vector, samples):
    best_match = None
    highest_score = -1

    for label, sample_vector in samples.items():
        score = get_cosine_similarity(user_query_vector, np.array(sample_vector))
        if score > highest_score:
            highest_score = score
            best_match = label

    return best_match, highest_score

# 4. SIMULATION (The "Real World" Example)
# Imagine a lead just typed something that converts to this vector:
new_lead_query = np.array([0.15, 0.75, 0.25])

match, confidence = find_top_match(new_lead_query, knowledge_base)

# OUTPUT
print("--- KeaBuilder Smart Matcher ---")
print(f"Incoming Query Vector: {new_lead_query}")
print(f"Top System Match: {match}")
print(f"Confidence Score: {confidence:.4f}")